### PR TITLE
Updated dependencies to allow usage of Kotlin 1.9, AGP 8+ and latest …

### PR DESCRIPTION
**Pull request by nunofvalente**
…Compose version

## Issue

[issue#208](https://github.com/checkout/frames-android/issues/208)

## Proposed changes

Frames SDK contains a lot of dependencies that are old and are an obstacle for companies to upgrade their codebases to use the latest dependencies as it is usually not supported by this SDK.

As we want to migrate to the newest Kotlin, AGP and Compose version we need Frames to be able to handle these versions as it was crashing our app. There is already an issue where people are not able to update their dependencies due to conflicts.

Migrated following dependecies:
- Dagger
- AGP 8.1.0
- Kotlin to 1.9
- Compose dependencies
- Mockk
- Other dependencies that were affected by these changes.

The application now compiles with Java 17 instead of Java 8 as it is a requirement for AGP 8.1.0.

## Test Steps

All the tests have passed. Didn't introduce new code, only changed what was not supported or deprecated.
I have tested the apps and they were working fine.

## Checklist

* [ ] Reviewers assigned
* [x] I have performed a self-review of my code and manual testing
* [x] Lint and unit tests pass locally with my changes
* [ ] I have added tests that prove my fix is effective or that my feature works
* [x] I have added necessary documentation (if applicable)

## Further comments

Most of the files were probably due to me optimising the imports.

MonochromeLauncherIcon lint issue is due to not having a monochromatic icon. 
More information here: [MonochromeLauncherIcon](https://googlesamples.github.io/android-custom-lint-rules/checks/MonochromeLauncherIcon.md.html)

### CODE REVIEW

**Comment by chintan-soni-cko** [comment]
@nunofvalente Thanks for raising this PR. We will review it, and prioritise this tech stack upgrade soon for our future releases.

**Comment by patrick-hoban-cko** [comment]
Hey @PuhalschiAlexandru, we do plan to start making this upgrade next week once we finish some other priority work.

I'll come back on here once we have more concrete timelines for releasing a new version of our Frames Android SDK. Thank you for your patience in the meantime!

**Comment by fabio-insolia-cko** [comment]
This PR is done as part of https://github.com/checkout/frames-android/pull/245

**Comment by chintan-soni-cko** [comment]
@nunofvalente, we have now made release [4.2.0](https://github.com/checkout/frames-android/releases/tag/4.2.0) of the SDK which includes some major upgrades for key dependencies.

**Pull request closed without merging**
